- hosts: localhost
  pre_tasks:
  - name: Upgrade all packages
    become: true
    ansible.builtin.dnf:
      name: "*"
      state: latest
  - name: Autoremove unneeded packages installed as dependencies
    become: true
    ansible.builtin.dnf:
      autoremove: yes

  - import_tasks: tasks/core.yml
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/nvim.yml
  - import_tasks: tasks/docker.yml
