- name: Install Bash 
  become: true
  ansible.builtin.dnf: name=bash
  tags: &tags_for_bash_tasks [ 'install', 'productivity', 'dotfiles', 'bash' ]

- name: Change shell to bash 
  become: true
  user:
    name: "josh"
    shell: /bin/bash
  tags: *tags_for_bash_tasks    
