- name: Install core packages
  become: true
  ansible.builtin.dnf:
    name: 
      - bat
      - ccache
      - clang
      - clipit
      - dnf-plugins-core
      - feh 
      - fonts-firacode
      - fzf
      - gimp
      - golang
      - gradle
      - htop
      - i3
      - kitty
      - nodejs
      - npm
      - picom
      - python3-pip 
      - ripgrep
      - rofi
      - texstudio
      - timeshift
      - tmux 
      - xbacklight
      - zsh 
  tags:
    - install
    - core
