- name: Install core packages
  become: true
  ansible.builtin.dnf:
    name: 
      - bat
      - cargo
      - ccache
      - clang
      - clipit
      - dnf-plugins-core
      - feh 
      - fira-code-fonts
      - fontawesome-fonts
      - mozilla-fira-mono-fonts
      - fzf
      - gimp
      - golang
      - htop
      - i3
      - kitty
      - nodejs
      - npm
      - picom
      - python3-pip 
      - ripgrep
      - rofi
      - rust
      - texstudio
      - timeshift
      - tmux 
      - xbacklight
      - xclip
      - zeal
      - zsh 
  tags:
    - install
    - core

- name: Install pytest and dependencies
  shell: python3 -m pip install pytest pytest-cache pytest-subtests pytest-pylint
