- name: Install System Packages
  become: true
  ansible.builtin.dnf:
    name: [ "nodejs", "npm", "kitty", "rofi", "clang", "picom", "curl", "htop", "tmux", "fzf", "golang", "i3", "ccache", "ninja-build", "python3-pip", "zsh"]
  tags:
    - install
    - core

- name: Install nvim deps 
  become: true
  ansible.builtin.dnf:
    name: [ "ninja-build", "gettext", "libtool", "autoconf", "automake", "cmake", "gcc", "gcc-c++", "make", "pkg-config", "unzip", "patch", "curl", "doxygen"]
  tags:
    - install
    - neovim
    - core
