- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2
  become: true
  apt:
    name: [ "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3
  become: true
  apt:
    name: [ "picom", "curl", "htop", "tmux", "fzf", "yarn", "golang", "i3", "ccache", "ninja-build", "python3-pip", "clangd", "zsh"]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: ["clang"]
  tags:
    - install
    - neovim
    - core
