- name: Install cmake 
  become: true
  ansible.builtin.dnf:
    name: ["cmake"]
  tags:
    - install
    - neovim
    - core

- name: Install unzip 
  become: true
  ansible.builtin.dnf:
    name: [ "unzip"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3
  become: true
  ansible.builtin.dnf:
    name: [ "picom", "curl", "htop", "tmux", "fzf", "yarn", "golang", "i3", "ccache", "ninja-build", "python3-pip", "clangd", "zsh"]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  ansible.builtin.dnf:
    name: ["clang"]
  tags:
    - install
    - neovim
    - core
