- name: Remove old versions 
  become: true
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent 

- name: Add docker repo 
  become: true
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker 
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

